version: '3.8'

services:
  driver-bot:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - driver-network

networks:
  driver-network:
    driver: bridge

volumes:
  data: 