version: '3.8'

services:
  clever-driver-bot:
    build: .
    container_name: clever-driver-bot
    ports:
      - "8443:8443"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./geo_locations.json:/app/geo_locations.json:ro
    restart: unless-stopped
    networks:
      - clever-bot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost:8443/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  clever-bot-network:
    driver: bridge 